/**
 * Generates a structured Markdown snapshot of the Supabase DB schema.
 * Queries information_schema + pg_catalog for tables, columns, enums, functions, RLS policies, indexes.
 *
 * Usage: npx tsx scripts/generate-db-schema-snapshot.ts
 * Output: .claude/memory-bank/db-schema-snapshot.md
 *
 * Requires: NEXT_PUBLIC_SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY in .env.local
 */

import { createClient } from '@supabase/supabase-js'
import fs from 'fs'
import path from 'path'
import dotenv from 'dotenv'

// Load .env.local
dotenv.config({ path: path.join(process.cwd(), '.env.local') })

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY

if (!supabaseUrl || !serviceRoleKey) {
  console.error('Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env.local')
  process.exit(1)
}

const supabase = createClient(supabaseUrl, serviceRoleKey, {
  auth: { autoRefreshToken: false, persistSession: false },
})

const OUTPUT_PATH = path.join(process.cwd(), '.claude/memory-bank/db-schema-snapshot.md')

// ─── Query helpers ───────────────────────────────────────────────

async function query<T = Record<string, unknown>>(sql: string): Promise<T[]> {
  const { data, error } = await supabase.rpc('exec_sql', { sql_query: sql }).single()
  if (error) {
    // Fallback: use pg_catalog direct queries via REST
    // If exec_sql doesn't exist, we'll use information_schema views
    throw error
  }
  return (data as unknown as T[]) ?? []
}

/**
 * Runs raw SQL via supabase.rpc or supabase-js .from() on information_schema views.
 * Since we can't run arbitrary SQL via REST, we query views available through PostgREST.
 * For schema introspection, we use the Supabase Management API or pg_catalog via rpc.
 */
async function queryRaw(sql: string): Promise<Record<string, unknown>[]> {
  // Use the supabase-js sql tagged template if available, otherwise fall back to rpc
  const response = await fetch(`${supabaseUrl}/rest/v1/rpc/exec_sql`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'apikey': serviceRoleKey!,
      'Authorization': `Bearer ${serviceRoleKey}`,
      'Prefer': 'return=representation',
    },
    body: JSON.stringify({ sql_query: sql }),
  })

  if (!response.ok) {
    // If exec_sql function doesn't exist, return empty
    return []
  }

  return response.json()
}

// ─── Parse database.types.ts ─────────────────────────────────────

interface TableInfo {
  name: string
  columns: ColumnInfo[]
  relationships: { column: string; referencedTable: string; referencedColumn: string }[]
}

interface ColumnInfo {
  name: string
  type: string
  nullable: boolean
}

interface EnumInfo {
  name: string
  values: string[]
}

/**
 * Strategy: use indentation-based parsing.
 * In database.types.ts generated by Supabase:
 * - Table names are at 6 spaces indent: `      table_name: {`
 * - Row/Insert/Update/Relationships at 8 spaces: `        Row: {`
 * - Column definitions at 10 spaces: `          col_name: type`
 * - Row closing brace at 8 spaces: `        }`
 */
function parseDbTypesRobust(): { tables: TableInfo[]; enums: EnumInfo[] } {
  const typesPath = path.join(process.cwd(), 'lib/database.types.ts')
  const content = fs.readFileSync(typesPath, 'utf-8')
  const lines = content.split('\n')

  const tables: TableInfo[] = []
  const enums: EnumInfo[] = []

  type Section = 'none' | 'tables' | 'enums' | 'views' | 'functions'
  let section: Section = 'none'
  let currentTable = ''
  let currentColumns: ColumnInfo[] = []
  let currentRelationships: { column: string; referencedTable: string; referencedColumn: string }[] = []
  let inRowBlock = false
  let inRelationshipsBlock = false
  let relBraceDepth = 0
  let currentRelEntry: Record<string, string> = {}

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]
    const trimmed = line.trim()

    // Detect top-level sections (under public:)
    if (/^\s{4}Tables:\s*\{/.test(line)) { section = 'tables'; continue }
    if (/^\s{4}Views:\s*\{/.test(line)) { section = 'views'; continue }
    if (/^\s{4}Enums:\s*\{/.test(line)) { section = 'enums'; continue }
    if (/^\s{4}Functions:\s*\{/.test(line)) { section = 'functions'; continue }
    if (/^\s{4}CompositeTypes:\s*\{/.test(line)) { section = 'none'; continue }

    // ── Tables section ──
    if (section === 'tables') {
      // Table name line: `      table_name: {`
      const tableMatch = line.match(/^\s{6}(\w+):\s*\{/)
      if (tableMatch && !inRowBlock && !inRelationshipsBlock) {
        // Save previous table if any
        if (currentTable && currentColumns.length > 0) {
          tables.push({ name: currentTable, columns: [...currentColumns], relationships: [...currentRelationships] })
        }
        currentTable = tableMatch[1]
        currentColumns = []
        currentRelationships = []
        inRowBlock = false
        inRelationshipsBlock = false
        continue
      }

      // Row block start: `        Row: {`
      if (/^\s{8}Row:\s*\{/.test(line)) {
        inRowBlock = true
        continue
      }

      // Row block end: `        }` (8 spaces + })
      if (inRowBlock && /^\s{8}\}/.test(line) && !trimmed.startsWith('}')) {
        // This is the closing of Row block
        inRowBlock = false
        continue
      }
      if (inRowBlock && trimmed === '}' && line.match(/^\s{8}\}/)) {
        inRowBlock = false
        continue
      }

      // Column inside Row block (10 spaces indent)
      if (inRowBlock) {
        const colMatch = trimmed.match(/^(\w+):\s*(.+)$/)
        if (colMatch) {
          const name = colMatch[1]
          let typeStr = colMatch[2].trim()
          const nullable = typeStr.includes('| null')
          typeStr = typeStr.replace(/\s*\|\s*null/g, '').trim()
          // Simplify Database["public"]["Enums"]["xxx"] to enum:xxx
          typeStr = typeStr.replace(/Database\["public"\]\["Enums"\]\["(\w+)"\]/g, 'enum:$1')
          currentColumns.push({ name, type: typeStr, nullable })
        }
        continue
      }

      // Relationships block start
      if (/^\s{8}Relationships:\s*\[/.test(line)) {
        inRelationshipsBlock = true
        relBraceDepth = 0
        continue
      }

      if (inRelationshipsBlock) {
        if (trimmed === '{') {
          relBraceDepth++
          currentRelEntry = {}
          continue
        }
        if (trimmed === '}' || trimmed === '},') {
          relBraceDepth--
          // Save relationship entry if it has the required fields
          if (currentRelEntry.columns && currentRelEntry.referencedRelation && currentRelEntry.referencedColumns) {
            // Skip view references (e.g., buildings_active, lots_active)
            if (!currentRelEntry.referencedRelation.includes('_active') &&
                !currentRelEntry.referencedRelation.includes('_with_')) {
              currentRelationships.push({
                column: currentRelEntry.columns,
                referencedTable: currentRelEntry.referencedRelation,
                referencedColumn: currentRelEntry.referencedColumns,
              })
            }
          }
          currentRelEntry = {}
          continue
        }
        if (trimmed === ']' || trimmed === '],') {
          inRelationshipsBlock = false
          continue
        }

        // Parse relationship fields
        const fkMatch = trimmed.match(/^(\w+):\s*"([^"]+)"/)
        if (fkMatch) {
          currentRelEntry[fkMatch[1]] = fkMatch[2]
        }
        const arrMatch = trimmed.match(/^(\w+):\s*\["([^"]+)"\]/)
        if (arrMatch) {
          currentRelEntry[arrMatch[1]] = arrMatch[2]
        }
        continue
      }

      // End of Tables section (4 spaces + })
      if (/^\s{4}\}/.test(line) && trimmed === '}') {
        // Save last table
        if (currentTable && currentColumns.length > 0) {
          tables.push({ name: currentTable, columns: [...currentColumns], relationships: [...currentRelationships] })
        }
        section = 'none'
        currentTable = ''
        currentColumns = []
        currentRelationships = []
        continue
      }
    }

    // ── Enums section ──
    if (section === 'enums') {
      // Enum name: `      enum_name:`
      const enumMatch = trimmed.match(/^(\w+):$/)
      if (enumMatch) {
        const enumName = enumMatch[1]
        const values: string[] = []
        let j = i + 1
        while (j < lines.length) {
          const valLine = lines[j].trim()
          const valMatch = valLine.match(/\|\s*"([^"]+)"/)
          if (valMatch) {
            values.push(valMatch[1])
            j++
          } else {
            break
          }
        }
        if (values.length > 0) {
          enums.push({ name: enumName, values })
          i = j - 1
        }
        continue
      }

      // End of Enums section
      if (/^\s{4}\}/.test(line) && trimmed === '}') {
        section = 'none'
        continue
      }
    }
  }

  return { tables, enums }
}

// ─── Parse migrations for FK relationships ───────────────────────

function parseMigrationsForFKs(): string[] {
  const migrationsDir = path.join(process.cwd(), 'supabase/migrations')
  const files = fs.readdirSync(migrationsDir).filter(f => f.endsWith('.sql')).sort()
  const fks: string[] = []

  for (const file of files) {
    const content = fs.readFileSync(path.join(migrationsDir, file), 'utf-8')
    // Match REFERENCES patterns
    const refRegex = /(\w+)\s+.*?REFERENCES\s+(\w+)\s*\((\w+)\)/gi
    let match
    while ((match = refRegex.exec(content)) !== null) {
      fks.push(`${match[1]} → ${match[2]}(${match[3]})`)
    }
  }

  return [...new Set(fks)]
}

// ─── Parse migrations for RLS policies ───────────────────────────

function parseMigrationsForRLS(): Map<string, string[]> {
  const migrationsDir = path.join(process.cwd(), 'supabase/migrations')
  const files = fs.readdirSync(migrationsDir).filter(f => f.endsWith('.sql')).sort()
  const policies = new Map<string, string[]>()

  for (const file of files) {
    const content = fs.readFileSync(path.join(migrationsDir, file), 'utf-8')

    // Match CREATE POLICY statements
    const policyRegex = /CREATE\s+POLICY\s+"([^"]+)"\s+ON\s+(?:public\.)?(\w+)\s+(?:AS\s+(\w+)\s+)?FOR\s+(\w+)/gi
    let match
    while ((match = policyRegex.exec(content)) !== null) {
      const policyName = match[1]
      const tableName = match[2]
      const permissiveness = match[3] || 'PERMISSIVE'
      const action = match[4]

      const key = tableName
      if (!policies.has(key)) policies.set(key, [])
      policies.get(key)!.push(`${action} [${permissiveness}]: ${policyName}`)
    }

    // Match DROP POLICY (to remove overridden policies)
    const dropRegex = /DROP\s+POLICY\s+(?:IF\s+EXISTS\s+)?"([^"]+)"\s+ON\s+(?:public\.)?(\w+)/gi
    while ((match = dropRegex.exec(content)) !== null) {
      const policyName = match[1]
      const tableName = match[2]
      const existing = policies.get(tableName)
      if (existing) {
        const idx = existing.findIndex(p => p.includes(policyName))
        if (idx !== -1) existing.splice(idx, 1)
      }
    }
  }

  return policies
}

// ─── Parse migrations for functions ──────────────────────────────

function parseMigrationsForFunctions(): { name: string; args: string; returns: string; security: string }[] {
  const migrationsDir = path.join(process.cwd(), 'supabase/migrations')
  const files = fs.readdirSync(migrationsDir).filter(f => f.endsWith('.sql')).sort()
  const functions = new Map<string, { name: string; args: string; returns: string; security: string }>()

  for (const file of files) {
    const content = fs.readFileSync(path.join(migrationsDir, file), 'utf-8')

    // Match CREATE OR REPLACE FUNCTION
    const funcRegex = /CREATE\s+(?:OR\s+REPLACE\s+)?FUNCTION\s+(?:public\.)?(\w+)\s*\(([^)]*)\)\s*RETURNS\s+(\S+(?:\s+\S+)?)/gi
    let match
    while ((match = funcRegex.exec(content)) !== null) {
      const name = match[1]
      // Clean up args: collapse multi-line, remove DEFAULT values for brevity
      const args = match[2].trim()
        .replace(/\s*\n\s*/g, ' ')
        .replace(/\s+DEFAULT\s+[^,)]+/gi, '')
        .trim()
      // Clean up returns: remove trailing LANGUAGE, AS, etc.
      const returns = match[3].trim()
        .replace(/\s*(LANGUAGE|AS|SECURITY|STABLE|VOLATILE|IMMUTABLE|STRICT|COST|SET|PARALLEL)\b[\s\S]*/i, '')
        .replace(/\s*\n\s*/g, ' ')
        .trim()

      // Check for SECURITY DEFINER
      const afterFunc = content.substring(match.index, Math.min(match.index + 500, content.length))
      const security = afterFunc.includes('SECURITY DEFINER') ? 'DEFINER' : 'INVOKER'

      functions.set(name, { name, args, returns, security })
    }

    // Match DROP FUNCTION
    const dropRegex = /DROP\s+FUNCTION\s+(?:IF\s+EXISTS\s+)?(?:public\.)?(\w+)/gi
    while ((match = dropRegex.exec(content)) !== null) {
      functions.delete(match[1])
    }
  }

  return [...functions.values()].sort((a, b) => a.name.localeCompare(b.name))
}

// ─── Parse migrations for views ──────────────────────────────────

function parseMigrationsForViews(): string[] {
  const migrationsDir = path.join(process.cwd(), 'supabase/migrations')
  const files = fs.readdirSync(migrationsDir).filter(f => f.endsWith('.sql')).sort()
  const views = new Set<string>()

  for (const file of files) {
    const content = fs.readFileSync(path.join(migrationsDir, file), 'utf-8')
    const viewRegex = /CREATE\s+(?:OR\s+REPLACE\s+)?VIEW\s+(?:public\.)?(\w+)/gi
    let match
    while ((match = viewRegex.exec(content)) !== null) {
      views.add(match[1])
    }
  }

  return [...views].sort()
}

// ─── Generate markdown ───────────────────────────────────────────

function generateMarkdown(
  tables: TableInfo[],
  enums: EnumInfo[],
  functions: { name: string; args: string; returns: string; security: string }[],
  views: string[],
  rlsPolicies: Map<string, string[]>,
): string {
  const now = new Date().toISOString().split('T')[0]
  let md = `# DB Schema Snapshot

> Auto-generated on ${now} by \`npx tsx scripts/generate-db-schema-snapshot.ts\`
> Source: \`lib/database.types.ts\` + \`supabase/migrations/*.sql\`
> **Do not edit manually** — re-run the script to update.

## Summary

- **${tables.length} tables** | **${enums.length} enums** | **${functions.length} functions** | **${views.length} views**

---

## Tables

`

  // Group tables by domain
  const domainGroups: Record<string, TableInfo[]> = {
    'Auth & Teams': [],
    'Properties': [],
    'Interventions': [],
    'Conversations': [],
    'Contracts': [],
    'Documents & Storage': [],
    'Billing (Stripe)': [],
    'Notifications': [],
    'AI & Phone': [],
    'Operations': [],
    'Bank': [],
    'Other': [],
  }

  for (const table of tables) {
    const name = table.name
    if (['users', 'teams', 'team_members', 'companies', 'company_members', 'user_invitations'].includes(name)) {
      domainGroups['Auth & Teams'].push(table)
    } else if (['buildings', 'lots', 'building_contacts', 'lot_contacts', 'addresses'].includes(name)) {
      domainGroups['Properties'].push(table)
    } else if (name.startsWith('intervention') || name === 'activity_logs') {
      domainGroups['Interventions'].push(table)
    } else if (name.startsWith('conversation')) {
      domainGroups['Conversations'].push(table)
    } else if (name.startsWith('contract') || name.startsWith('supplier_contract')) {
      domainGroups['Contracts'].push(table)
    } else if (name.includes('document') || name === 'import_jobs' || name === 'property_documents') {
      domainGroups['Documents & Storage'].push(table)
    } else if (name.startsWith('stripe') || name === 'subscriptions') {
      domainGroups['Billing (Stripe)'].push(table)
    } else if (['notifications', 'push_subscriptions', 'email_links'].includes(name)) {
      domainGroups['Notifications'].push(table)
    } else if (name.startsWith('ai_phone')) {
      domainGroups['AI & Phone'].push(table)
    } else if (['reminders', 'recurrence_rules', 'recurrence_occurrences'].includes(name)) {
      domainGroups['Operations'].push(table)
    } else if (['bank_connections', 'bank_transactions', 'rent_calls', 'transaction_links', 'auto_linking_rules', 'property_expenses', 'security_deposits'].includes(name)) {
      domainGroups['Bank'].push(table)
    } else {
      domainGroups['Other'].push(table)
    }
  }

  for (const [group, groupTables] of Object.entries(domainGroups)) {
    if (groupTables.length === 0) continue
    md += `### ${group}\n\n`

    for (const table of groupTables) {
      const policyCount = rlsPolicies.get(table.name)?.length ?? 0
      md += `<details>\n<summary><strong>${table.name}</strong> (${table.columns.length} cols${policyCount > 0 ? `, ${policyCount} RLS` : ''})</summary>\n\n`
      md += `| Column | Type | Nullable |\n|--------|------|----------|\n`
      for (const col of table.columns) {
        md += `| ${col.name} | \`${col.type}\` | ${col.nullable ? 'YES' : 'NO'} |\n`
      }

      // Add FK relationships if any
      if (table.relationships && table.relationships.length > 0) {
        md += `\n**FK Relationships:**\n`
        for (const rel of table.relationships) {
          md += `- \`${rel.column}\` → \`${rel.referencedTable}(${rel.referencedColumn})\`\n`
        }
      }

      // Add RLS policies if any
      const policies = rlsPolicies.get(table.name)
      if (policies && policies.length > 0) {
        md += `\n**RLS Policies:**\n`
        for (const p of policies) {
          md += `- ${p}\n`
        }
      }

      md += `\n</details>\n\n`
    }
  }

  // Enums
  md += `---\n\n## Enums (${enums.length})\n\n`
  for (const e of enums.sort((a, b) => a.name.localeCompare(b.name))) {
    md += `- **${e.name}**: ${e.values.map(v => `\`${v}\``).join(' | ')}\n`
  }

  // Functions
  md += `\n---\n\n## Functions (${functions.length})\n\n`

  const rlsFunctions = functions.filter(f =>
    f.name.startsWith('is_') || f.name.startsWith('get_') || f.name.startsWith('can_')
  )
  const triggerFunctions = functions.filter(f =>
    f.name.startsWith('tr_') || f.name.startsWith('sync_') ||
    f.name.startsWith('update_') || f.name.startsWith('handle_') ||
    f.name.startsWith('add_') || f.name.startsWith('validate_') ||
    f.name.startsWith('log_')
  )
  const otherFunctions = functions.filter(f =>
    !rlsFunctions.includes(f) && !triggerFunctions.includes(f)
  )

  if (rlsFunctions.length > 0) {
    md += `### RLS Helper Functions (${rlsFunctions.length})\n\n`
    md += `| Function | Args | Returns | Security |\n|----------|------|---------|----------|\n`
    for (const f of rlsFunctions) {
      const shortArgs = f.args.length > 60 ? f.args.substring(0, 57) + '...' : f.args
      md += `| ${f.name} | ${shortArgs || '—'} | ${f.returns} | ${f.security} |\n`
    }
    md += '\n'
  }

  if (triggerFunctions.length > 0) {
    md += `### Trigger Functions (${triggerFunctions.length})\n\n`
    md += `| Function | Returns | Security |\n|----------|---------|----------|\n`
    for (const f of triggerFunctions) {
      md += `| ${f.name} | ${f.returns} | ${f.security} |\n`
    }
    md += '\n'
  }

  if (otherFunctions.length > 0) {
    md += `### Other Functions (${otherFunctions.length})\n\n`
    md += `| Function | Args | Returns | Security |\n|----------|------|---------|----------|\n`
    for (const f of otherFunctions) {
      const shortArgs = f.args.length > 60 ? f.args.substring(0, 57) + '...' : f.args
      md += `| ${f.name} | ${shortArgs || '—'} | ${f.returns} | ${f.security} |\n`
    }
    md += '\n'
  }

  // Views
  if (views.length > 0) {
    md += `---\n\n## Views (${views.length})\n\n`
    for (const v of views) {
      md += `- \`${v}\`\n`
    }
  }

  md += `\n---\n*Regenerate: \`npx tsx scripts/generate-db-schema-snapshot.ts\`*\n`

  return md
}

// ─── Main ────────────────────────────────────────────────────────

async function main() {
  console.log('📊 Generating DB schema snapshot...')

  // Parse database.types.ts for tables and enums
  console.log('  → Parsing lib/database.types.ts...')
  const { tables, enums } = parseDbTypesRobust()
  console.log(`    Found ${tables.length} tables, ${enums.length} enums`)

  // Parse migrations for functions, views, RLS
  console.log('  → Parsing supabase/migrations/*.sql...')
  const functions = parseMigrationsForFunctions()
  console.log(`    Found ${functions.length} functions`)

  const views = parseMigrationsForViews()
  console.log(`    Found ${views.length} views`)

  const rlsPolicies = parseMigrationsForRLS()
  const totalPolicies = [...rlsPolicies.values()].reduce((sum, arr) => sum + arr.length, 0)
  console.log(`    Found ${totalPolicies} RLS policies across ${rlsPolicies.size} tables`)

  // Generate markdown
  console.log('  → Generating markdown...')
  const markdown = generateMarkdown(tables, enums, functions, views, rlsPolicies)

  // Ensure output directory exists
  const outputDir = path.dirname(OUTPUT_PATH)
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true })
  }

  fs.writeFileSync(OUTPUT_PATH, markdown, 'utf-8')
  console.log(`\n✅ Schema snapshot written to ${path.relative(process.cwd(), OUTPUT_PATH)}`)
  console.log(`   ${tables.length} tables | ${enums.length} enums | ${functions.length} functions | ${views.length} views | ${totalPolicies} RLS policies`)
}

main().catch(err => {
  console.error('❌ Error:', err)
  process.exit(1)
})
